server:
  port:
  ssl:
    key-store:
    key-store-password:
    key-alias:
webservice:
  name: API Throttling
throttling:
  read:
    minute: 10
    hour: 10
    day: 100
  search:
    minute: 10
    hour: 10
    day: 100